[package]
name = "liquid-address"
version = "0.1.0"
edition = "2021"

[dependencies]
boltz-client = { git = "https://github.com/andrei-21/boltz-rust", branch = "fix/error-visibility" }
rocket = "0.5.0"
serde_json = "1.0.114"
threadpool = "1.8.1"
ureq = "2.9.6"
