[package]
name = "liquid-address"
version = "0.1.0"
edition = "2021"

[dependencies]
boltz-client = { path = "../boltz-rust" }
serde_json = "1.0.114"
threadpool = "1.8.1"
tokio = { version = "1.36.0", features = ["full"] }
ureq = "2.9.6"
